version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:  # Choose any name, such as `build`
    # The primary container, where your job's commands will run
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: Create Cloudformation Stack
          command: | 
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["ee:d4:96:0f:c4:35:a4:40:d7:31:61:88:6d:5e:89:8c"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
              ansible-playbook -i inventory-file.txt main-remote.yml
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure:
            requires: 
             - create_infrastructure


